session_db:
  container_name: session_db
  image: mongo
  net: ${NETWORK}
    
booking_db:
  container_name: booking_db
  image: mongo
  net: ${NETWORK}
    
customer_db:
  container_name: customer_db
  image: mongo
  net: ${NETWORK}
    
flight_db:
  container_name: flight_db
  image: mongo
  net: ${NETWORK}

main_service_node1: 
  container_name: main_service_node1
  build: .
  dockerfile: Dockerfile_main
  net: ${NETWORK}

auth_service_node1:
  container_name: auth_service_node1
  build: .
  dockerfile: Dockerfile_as
  net: ${NETWORK}
  volumes_from:
    - session_db

booking_service_node1:
  container_name: booking_service_node1
  build: .
  dockerfile: Dockerfile_bs
  net: ${NETWORK}
  volumes_from:
    - booking_db

customer_service_node1:
  container_name: customer_service_node1
  build: .
  dockerfile: Dockerfile_cs
  net: ${NETWORK}
  volumes_from:
    - customer_db

flight_service_node1:
  container_name: flight_service_node1
  build: .
  dockerfile: Dockerfile_fs
  net: ${NETWORK}
  volumes_from:
    - flight_db
    
#support_service_node1:
#  container_name: support_service_node1
#  build: .
#  dockerfile: Dockerfile_ss
#  net: ${NETWORK}
    
nginx:
  container_name: nginx
  restart: always
  build: ./nginx/
  net: ${NETWORK}
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - main_service_node1
    - auth_service_node1
    - booking_service_node1
    - customer_service_node1
    - flight_service_node1
 #   - support_service_node1
