db:
  container_name: mongo
  image: mongo
  net: ${NETWORK}
  ports:
    - 27017:27017

nginx:
  container_name: nginx
  restart: always
  build: ./nginx/
  net: ${NETWORK}
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - node1
    - node2
    - node3
    - node4
    - node5

node1: 
  container_name: node1
  build: .
  dockerfile: Dockerfile_main
  net: ${NETWORK}
  volumes:
    - "./:/src/"

node2:
  container_name: node2
  build: .
  dockerfile: Dockerfile_as
  net: ${NETWORK}
  volumes:
    - "./:/src/"

node3:
  container_name: node3
  build: .
  dockerfile: Dockerfile_bs
  net: ${NETWORK}
  volumes:
    - "./:/src/"

node4:
  container_name: node4
  build: .
  dockerfile: Dockerfile_cs
  net: ${NETWORK}
  volumes:
    - "./:/src/"

node5:
  container_name: node5
  build: .
  dockerfile: Dockerfile_fs
  net: ${NETWORK}
  volumes:
    - "./:/src/"
